name: Greet New PRs and Issues

on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  greet:
    runs-on: ubuntu-24.04
    steps:
        - name: :(
          uses: alex-sandri/nothing-action@v1.1
            
